name: Deploy The Wild Oasis

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/the_wild_oasis_website

            echo "Fetching latest changes..."
            git fetch --all
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Building Next.js project..."
            npm run build

            